#!/usr/bin/env python3
"""One-step pipeline: render PNG -> technical B/W -> traced silhouette SVG."""

import argparse
import os
import subprocess
import sys
import tempfile
from pathlib import Path

SILHOUETTE_PROMPT = (
    "Convert to a technical flat line drawing. Pure white background. "
    "Solid black outlines only, uniform stroke weight throughout. "
    "Every construction seam and panel boundary rendered as a distinct black line. "
    "Panel interiors solid white — no fill, no shading, no gradients, no texture. "
    "Garment silhouette edge in black. No labels, no annotations, no shadows. "
    "Result must be high-contrast black-on-white suitable for vector auto-tracing where each panel becomes a separate closed path."
)
POTRACE_BIN = "/opt/homebrew/bin/potrace"


def _run(cmd: list[str], dry_run: bool = False) -> None:
    print("$ " + " ".join(cmd))
    if dry_run:
        return
    subprocess.run(cmd, check=True)


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="generate_silhouette",
        description="Generate silhouette SVG from an input render PNG using Kontext + potrace.",
    )
    parser.add_argument("input_png", help="Input render image (.png)")
    parser.add_argument(
        "--output",
        default=None,
        help="Output SVG path (default: <input_dir>/silhouette.svg)",
    )
    parser.add_argument(
        "--keep-bw",
        action="store_true",
        help="Keep intermediate black/white PNG generated by Kontext.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed forwarded to kontext (default: 42).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print commands without running them.",
    )
    args = parser.parse_args()

    input_png = Path(args.input_png).expanduser().resolve()
    if not input_png.exists():
        print(f"Input image not found: {input_png}", file=sys.stderr)
        return 1

    output_svg = (
        Path(args.output).expanduser().resolve()
        if args.output
        else input_png.parent / "silhouette.svg"
    )
    output_svg.parent.mkdir(parents=True, exist_ok=True)

    fd, tmp_name = tempfile.mkstemp(prefix="silhouette-bw-", suffix=".png", dir=str(output_svg.parent))
    os.close(fd)
    Path(tmp_name).unlink(missing_ok=True)
    bw_png = Path(tmp_name)

    try:
        kontext_cmd = [
            "kontext",
            SILHOUETTE_PROMPT,
            "--input",
            str(input_png),
            "--output",
            str(bw_png),
            "--seed",
            str(args.seed),
        ]
        _run(kontext_cmd, dry_run=args.dry_run)

        potrace_cmd = [
            POTRACE_BIN,
            str(bw_png),
            "-s",
            "-o",
            str(output_svg),
        ]
        _run(potrace_cmd, dry_run=args.dry_run)
    except subprocess.CalledProcessError as exc:
        print(f"Subprocess failed with exit code {exc.returncode}: {exc.cmd}", file=sys.stderr)
        return exc.returncode or 1
    finally:
        if not args.keep_bw and not args.dry_run:
            bw_png.unlink(missing_ok=True)

    print(f"Wrote SVG: {output_svg}")
    if args.keep_bw:
        print(f"Kept intermediate B/W PNG: {bw_png}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
